### ISSUE TITLE
PowerControl Fork for 2.6.4?

### ISSUE THREAD

**Issue by SimpleHeuristics** [aarron-lee/gpd-win-tricks#3]
installed Bazzite on a 2024 GPD Win Mini. HHD conflicts with the latest version of power control 2.6.4 where fan control does work. Using your current fork based on 2.4.9 however doesn't appear to apply the fan curves unfortunately. Are there any other workarounds other than your fork at this time? I know it's documented as being used for personal use so probably won't be regularly updated.

**Comment by aarron-lee** [comment]
I plan on updating the fork once I can get it to work with the Desktop app https://github.com/aarron-lee/PowerControl-Electron

I've been busy and haven't had time to update this, but I can try to get around to doing it soon-ish.

**Comment by Trossaloss** [comment]
I have the same device and have pivoted to using PowerControl only instead of the power control fork + simpledeckytdp or HHD. Haven't had any issues.

Thanks for the work Aarron, this guide + resources is a lifesaver.

**Comment by aarron-lee** [comment]
PowerControl fork has been updated to latest 2.7.1
